# Generated by Django 3.0.3 on 2020-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sublin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=40)),
                ('class_co', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
