# Generated by Django 3.0.3 on 2020-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_co', models.CharField(max_length=30)),
                ('period', models.CharField(max_length=1)),
            ],
        ),
    ]
