# Generated by Django 3.0.3 on 2020-08-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0002_friday_monday_saturday_thursday_tuesday_wednesday'),
    ]

    operations = [
        migrations.AddField(
            model_name='friday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
        migrations.AddField(
            model_name='monday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
        migrations.AddField(
            model_name='saturday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
        migrations.AddField(
            model_name='thursday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
        migrations.AddField(
            model_name='tuesday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
        migrations.AddField(
            model_name='wednesday',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tt.sublin'),
        ),
    ]
